/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'gallery-white': 'rgb(var(--color-gallery-white-rgb, 255 255 255) / <alpha-value>)',
        'studio-mist': 'var(--color-studio-mist, #f5f5f7)',
        'paper-frost': 'var(--color-paper-frost, #fafafc)',
        'hairline-silver': 'var(--color-hairline-silver, #d6d6d6)',
        'control-gray': 'var(--color-control-gray, #e6e6e8)',
        ink: 'var(--color-ink, #1d1d1f)',
        slate: 'var(--color-slate, #707070)',
        steel: 'rgb(var(--color-steel-rgb, 134 134 139) / <alpha-value>)',
        'apple-blue': 'var(--color-apple-blue, #0066cc)',
        'pricing-blue': 'rgb(var(--color-pricing-blue-rgb, 0 113 227) / <alpha-value>)',
        'launch-orange': 'var(--color-launch-orange, #b64400)',
      },
      fontFamily: {
        'sf-display': [
          'SF Pro Display',
          '-apple-system',
          'BlinkMacSystemFont',
          'Inter',
          'Sarabun',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
        ],
        'sf-text': [
          'SF Pro Text',
          '-apple-system',
          'BlinkMacSystemFont',
          'Inter',
          'Sarabun',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
        ],
        sans: [
          'SF Pro Text',
          '-apple-system',
          'BlinkMacSystemFont',
          'Inter',
          'Sarabun',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
        ],
        arial: [
          'Arial',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
        ],
        mono: [
          'SF Mono',
          'Geist Mono',
          'JetBrains Mono',
          'ui-monospace',
          'Menlo',
          'monospace',
        ],
      },
      letterSpacing: {
        'hero': '-1.2px',
        'compact': '-0.12px',
        'body-sm': '-0.224px',
        'body': '-0.374px',
        'kicker': '0.231px',
        'nav-title': '0.228px',
      },
      borderRadius: {
        'card': '28px',
        'cards': '28px',
        'link': '10px',
        'pill': '36px',
        'input': '980px',
        'button': '9999px',
        'navigation': '20px',
      },
      boxShadow: {
        'subtle': 'rgb(230, 230, 232) 0px 0px 0px 1px',
        'subtle-2': 'rgb(134, 134, 139) 0px 0px 0px 1px',
      },
    },
  },
  plugins: [],
}
